/**
 * Browser PiP window titles sourced from locale files: Firefox
 * `pictureinpicture-player-title` (mozilla-l10n, 98 locales) and Chromium
 * `IDS_PICTURE_IN_PICTURE_TITLE_TEXT` (80 locales). Fetched 2026-09-01,
 * lowercased for exact matching. Regeneration details:
 * prototype/issue-133-probes/pip-titles.json.
 */
export const PIP_WINDOW_TITLES: ReadonlySet<string> = new Set([
    'aslaɣ n uvidyu',
    'attēls attēlā',
    'attēls-attēlā',
    'beeld-in-beeld',
    'bideoa beste leiho batean',
    'bild im bild',
    'bild-i-bild',
    'bild-im-bild',
    'bilde i bilde',
    'bilde-i-bilde',
    'bildo en bildo',
    'billede-i-billede',
    'dealbh am broinn deilbh',
    'ecrã no ecrã',
    'figura brenda figurës',
    'figurë brenda figurës',
    'gambar dalam gambar',
    'gambar-dalam-gambar',
    'görüntü içinde görüntü',
    'hình trong hình',
    'imachen sobre imachen',
    'imagen en imagen',
    'imagine în imagine',
    'imagine-in-imagine',
    'imatge sobre imatge',
    'imaxe en imaxe',
    'imaxe sobre imaxe',
    'immàgine-subra-immàgine',
    "incrustation d'image",
    'incrustation vidéo',
    'integreret billede',
    'isithombe-esithombeni',
    'kuva kuvassa',
    'kép a képben',
    'llun mewn llun',
    'llun-mewn-llun',
    'maletg-en-maletg',
    'mmàggini-nnâ-mmàggini',
    'mode pip (picture-in-picture)',
    'mynd í mynd',
    'mynd-í-mynd',
    'obraz v obraze',
    'obraz v obraze',
    'obraz w obrazie',
    'obraz w obrazie',
    'pantaila txiki gainjarria',
    'pantalla superposta',
    'pencere içinde pencere',
    'pencere i̇çinde pencere',
    'picha ndani ya picha',
    'pictiúr i bpictiúr',
    'pictur-in-pictur',
    'picture in picture',
    'picture-in-picture',
    'pilt pildis',
    'pilt-pildis',
    'pip 모드',
    'prent-in-prent',
    "sa ni'io' riña sa ni'io'",
    'scherm-in-scherm',
    'skeudenn-ouzh-skeudenn',
    'slika u slici',
    'slika v sliki',
    'slika-u-slici',
    'tasvir ustida tasvir',
    'vaizdas vaizde',
    'vaizdas-vaizde',
    "vatzib'al",
    'vidèo incrustada',
    'vídeo em janela flutuante',
    'wobraz-we-wobrazu',
    'ôbroz w ôbrazie',
    'şəkil içində şəkil',
    'şəkildə-şəkil',
    'εικόνα εντός εικόνας',
    'παράθεση εικόνων',
    'выява ў выяве',
    'відарыс у відарысе',
    'дэлгэцэн доторх дэлгэц',
    'зображення в зображенні',
    'картина в картината',
    'картинка в картинке',
    'картинка в картинці',
    'расм-дар-расм',
    'слика во слика',
    'слика у слици',
    'суреттегі сурет',
    'сүрөт ичиндеги сүрөт',
    'նկար նկարի մեջ',
    'նկարը նկարում',
    'նկար֊նկարում',
    'תמונה בתוך תמונה',
    'تصویر در تصویر',
    'تصویر میں تصویر',
    'تصویر وِچ تصویر',
    'تصویردرتصویر',
    'شؽوات من شؽوات',
    'فديو معترِض',
    'نافذة ضمن النافذة',
    'وێنە-لەناو-وێنە',
    'चित्रात-चित्र',
    'पिक्चर में पिक्चर',
    'पिक्चर-इन-पिक्चर',
    'सावगारि-गेजेरौ-सावगारि',
    'চিত্ৰৰ ভিতৰত চিত্ৰ',
    'ছবির মধ্যে ছবি',
    'ছবির-মধ্যে-ছবি',
    'ছবিৰ-ওপৰত-ছবি',
    'ਤਸਵੀਰ-ਚ-ਤਸਵੀਰ',
    'ਤਸਵੀਰ-ਵਿੱਚ-ਤਸਵੀਰ',
    'ચિત્ર-માં-ચિત્ર',
    'ચિત્રમાં ચિત્ર',
    'ଛବି ମଧ୍ୟରେ ଛବି',
    'ପିକଚର୍ ଇନ୍ ପିକଚର୍',
    'பிக்ச்சர்-இன்-பிக்ச்சர்',
    'చిత్రంలో చిత్రం',
    'ಚಿತ್ರದಲ್ಲಿ ಚಿತ್ರ',
    'ചിത്രത്തിനുള്ളിലെ ചിത്രം',
    'ചിത്രത്തിനുള്ളിൽ ചിത്രം',
    'ചിത്രത്തിൽ ചിത്രം',
    'පින්තූරය තුළ පින්තූරය',
    'පින්තූරය-තුළ-පින්තූරය',
    'රූපයෙන් රූපයට',
    'การแสดงภาพซ้อนภาพ',
    'ภาพซ้อนภาพ',
    'ສະແດງຜົນຊ້ອນກັນ',
    'ສະແດງຜົນຫຼາຍຢ່າງພ້ອມກັນ',
    'နှစ်ခုထပ်၍ကြည့်ခြင်း',
    'ရုပ်ပုံ -ထဲမှ- ရုပ်ပုံ',
    'გამოსახულება გამოსახულებაში',
    'ეკრანი-ეკრანში',
    'በሥዕል ላይ ሥዕል',
    'በሥዕል ውስጥ ሥዕል',
    'រូបក្នុងរូប',
    'រូបក្នុងរូប​',
    'ᱪᱤᱛᱟᱹᱨᱼᱵᱷᱤᱛᱨᱤᱼᱪᱤᱛᱟᱹᱨ',
    'ảnh trong ảnh',
    'ピクチャー イン ピクチャー',
    'ピクチャーインピクチャー',
    '子母畫面',
    '画中画',
    '畫中畫',
    '화면 속 화면',
])
